fix: allow empty import without error, fix search index export on accounts where it is disabled
amplience/dc-cli pull request #125
Opened 2022-01-26 16:44 UTC by rs-amp

This PR fixes an issue where empty import on certain commands would cause the command to error out, which would interrupt the clone command despite the import technically succeeding (as it didn't have to do anything).

This also fixes an issue where search index list would throw an exception if it is disabled on the target account. In this case, the export is now simply skipped.

2022-02-01 12:41 UTC, easen-amp requested changes

2022-02-01 12:41 UTC, easen-amp commented on src/commands/search-index/export.ts
> +    log.warn('Could not get Search Indexes for the given hub - they may be disabled.', e);
You should check the HAL link on the hub to see if search-indexes are available for that given Hub.

2022-02-01 16:50 UTC, rs-amp commented on src/commands/search-index/export.ts
> +    log.warn('Could not get Search Indexes for the given hub - they may be disabled.', e);
Actually, can just use `hasOwnProperty` with no need to cast.

2022-04-08 12:25 UTC, easen-amp approved these changes

2022-05-05 11:06 UTC, mdinning-amp approved these changes

2022-05-05 11:32 UTC, merged