feat: Import/Export Content Item commands
amplience/dc-cli pull request #58
Opened 2020-08-27 13:06 UTC by rs-amp

This PR adds commands for import/export. These are pretty complicated, so the testing is quite extensive but doesn't reach 100% yet on the import task.

<writing in progress>

2020-08-27 16:03 UTC, Benj0s approved these changes

2020-08-27 16:03 UTC, Benj0s commented on src/common/import/publish-queue.ts
> +    while (true) {
As discussed previously; we should limit the number of retries here

2020-08-28 13:59 UTC, rs-amp commented on src/commands/content-type-schema/__mocks__/readline.ts
> +      console.log(questionText);
It's to log the question in the console, with the other logs the program normally does. Jest suppresses these, but you can see them when running/debugging the test individually so it's still useful to have.

2020-08-28 16:24 UTC, rs-amp commented on src/common/content-item/content-dependancy-tree.ts
> +    // eslint-disable-next-line @typescript-eslint/no-explicit-any
The input to this function is a content body, but on recursive calls it is an object or array.

2020-09-01 08:21 UTC, rs-amp commented
Addressed feedback from Ben.

2020-09-07 14:09 UTC, rs-amp commented
I've made a few changes for hopefully the final pass:

- add --publish flag for export
- use cached schemas for top level type validation
- publishes now perform sequentially rather than concurrently

2020-09-08 07:53 UTC, easen-amp requested changes

2020-09-08 07:53 UTC, easen-amp commented on src/commands/content-item/export.ts
> +      const publishedVersion: number | undefined = (item.item as any).lastPublishedVersion;
You can use `ContentItem` instead of `any`

2020-09-08 07:53 UTC, easen-amp commented on src/common/content-item/amplience-schema-validator.ts
> +    const draft4 = require('ajv/lib/refs/json-schema-draft-04.json');
DC currently supports draft 4 and draft 7 as well as some bespoke settings that are not in the json-schema spec. This is normally maintained/managed server side, allowing us to add new features/fixes.

Do you require client side validation? Or is it an optimisation feature to speed up the import phase?

2020-09-08 07:53 UTC, easen-amp commented on src/common/content-item/content-dependancy-tree.ts
> +export class ContentDependancyTree {
I can't see any unit tests for this class

2020-09-08 07:53 UTC, easen-amp commented on src/common/content-item/content-dependancy-tree.ts
> +export class ContentDependancyTree {
After running the tests I can see there is coverage for this class, so I think it's indirectly tested from some of the integration tests. However, I would prefer more unit tests and less integration tests - https://martinfowler.com/articles/practical-test-pyramid.html

2020-09-08 15:35 UTC, rs-amp commented on src/commands/content-item/export.ts
> +      const publishedVersion: number | undefined = (item.item as any).lastPublishedVersion;
ContentItem does not define lastPublishedVersion.

2020-09-08 15:38 UTC, rs-amp commented on src/common/content-item/amplience-schema-validator.ts
> +    const draft4 = require('ajv/lib/refs/json-schema-draft-04.json');
It's used to provide warnings to a user that content being exported will not import correctly with the currently synced content types/schemas. Since you can sync a schema and make older content items invalid, it could be useful for identifying and troubleshooting content items that have become invalid as a result.

It's also used to check if setting missing dependancies as null causes a content item to be invalid. If it does, we ask the user to skip the content entirely instead.

2020-09-08 15:42 UTC, rs-amp commented on src/common/content-item/amplience-schema-validator.ts
> +    const draft4 = require('ajv/lib/refs/json-schema-draft-04.json');
Draft 7 is supported by default, draft 4 is added manually since I noticed some schemas used it. It seems to be working fine for all content currently in willow and our testing account, but since it doesn't make any _important_ decisions with the validator, I don't think it needs to be lock step with changes to the serverside validation.

2020-09-08 15:43 UTC, rs-amp commented on src/common/content-item/content-dependancy-tree.ts
> +export class ContentDependancyTree {
That is true, content dependancy logic is tested mostly by the export and import class tests. I can add tests for this class on its own, but it will take some time.

2020-09-10 08:18 UTC, easen-amp commented on src/commands/content-item/export.ts
> +      const publishedVersion: number | undefined = (item.item as any).lastPublishedVersion;
Ok, in that case my preference would be to add/expose the `lastPublishedVersion` property on the `ContentItem` class in the DC Management SDK

2020-09-10 08:20 UTC, easen-amp commented on src/common/content-item/content-dependancy-tree.ts
> +export class ContentDependancyTree {
I think that would be useful as you might catch an edge case that your integration tests have missed.

2020-09-14 09:32 UTC, rs-amp commented
I've introduced tests for content-dependancy-tree, which includes the following changes:

- Dependancy levels are now strict: before two items would be in the same level if the dependancy was processed before the dependant. This is fine when processing levels synchronously and in order, but that assumption might be broken in future.
- Some renames and cleanup in the content-dependancy-tree class.
- `PublishedContentItem` interface introduced. This includes lastPublishedVersion and lastPublishedDate. In future these should be added to dc-management-sdk.

2020-09-21 13:53 UTC, easen-amp approved these changes

2020-09-30 10:42 UTC, merged