feat(content-item): archive/unarchive content item commands
amplience/dc-cli pull request #60
Opened 2020-10-02 14:19 UTC by PikinerLiliya

This PR adds commands for **archive/unarchive** of content item.

You can archive by exact **content item ID**, **name** or by **repository ID**, **folder ID**, **content type URI**. Regex arguments are passed with forward slashes on either side, though when they contain spaces they still must be passed with quotes surrounding them like any other string argument (eg. `"/regex with space/"`). Not providing any argument will perform the action on **all content items** through all repositories in a specified hub, which can be useful.

The user is given a summary of all actions that will be taken in the command line, and must answer (y/n) for the action to be taken. If the user passes the `--force` argument, the answer `y` will be assumed.

These commands output a **"revert log"**, which is a log file that describes all the actions that were taken in a format both readable to people, and readable to the dc-cli itself to revert any action taken at a later date. A log produced by an archive command can be used later by an unarchive command to undo all archives done by the previous action. This philosophy will carry forward into future PRs that have actions we might want to reverse.

The output location of the log file defaults to a a subfolder called logs/ in the .amplience/ folder used for configuration, but can be manually controlled with `--logFile <path>`. Either way, the log file path is printed when the command finishes executing, so that the user knows where their log is located. This log can be used in any future command by passing `--revertLog <path>`. Log files can be suppressed entirely by passing `--silent`.

2020-10-14 13:42 UTC, easen-amp requested changes

2020-10-14 13:42 UTC, easen-amp commented on src/commands/content-item/archive.ts
> +              contentItems = contentItems.concat(items.filter(item => item.status == 'ACTIVE'));
```
contentItems.push(...items.filter(item => item.status == 'ACTIVE'));
```

2020-10-14 13:42 UTC, easen-amp commented on src/commands/content-item/archive.ts
> +  let contentItems: ContentItem[] = [];
I would consider making `contentItems` const and call push() instead of using let & `.concat()` to add items

2020-10-14 13:42 UTC, easen-amp commented on src/commands/content-item/archive.ts
> +              contentItems = contentItems.concat(items);
`contentItems.push(...items);`

2020-10-14 13:42 UTC, easen-amp commented on src/commands/content-item/archive.ts
> +export const handler = async (argv: Arguments<ArchiveOptions & ConfigurationParameters>): Promise<void> => {
This method is fairly long and quite difficult to read, is it possible to break it down into smaller functions?

2020-10-14 13:42 UTC, easen-amp commented on src/commands/content-item/archive.ts
> +    if (revertLog != null) {
Each one of these if..else if statements could be moved into its own method, would make this easier to read.

2020-10-14 13:42 UTC, easen-amp commented on src/commands/content-item/unarchive.ts
> +export const handler = async (argv: Arguments<UnarchiveOptions & ConfigurationParameters>): Promise<void> => {
Same comment as before, this function could be broken down.

2020-10-16 13:03 UTC, PikinerLiliya commented on src/commands/content-item/archive.ts
> +              contentItems = contentItems.concat(items.filter(item => item.status == 'ACTIVE'));
Done

2020-10-16 13:03 UTC, PikinerLiliya commented on src/commands/content-item/archive.ts
> +  let contentItems: ContentItem[] = [];
Done

2020-10-16 13:03 UTC, PikinerLiliya commented on src/commands/content-item/archive.ts
> +              contentItems = contentItems.concat(items);
Done

2020-10-16 13:04 UTC, PikinerLiliya commented on src/commands/content-item/archive.ts
> +export const handler = async (argv: Arguments<ArchiveOptions & ConfigurationParameters>): Promise<void> => {
Done

2020-10-16 13:04 UTC, PikinerLiliya commented on src/commands/content-item/unarchive.ts
> +export const handler = async (argv: Arguments<UnarchiveOptions & ConfigurationParameters>): Promise<void> => {
Done

2020-10-16 13:56 UTC, easen-amp approved these changes

2020-10-22 11:45 UTC, rs-amp approved these changes
LGTM - I like the split up structure in the commands.

Just a single complaint about one of the option descriptions

2020-10-22 11:45 UTC, rs-amp commented on src/commands/content-item/archive.ts
> +        'The ID of a Content type to archive all content items.\nA single --contentType option may be given to match a single content type pattern.\nMultiple --contentType options may be given to mat
I don't like the first sentence here, and this is notably the Content Type Schema ID rather than the Content Type ID. Maybe:

`A pattern which will only archive content items with a matching Content Type Schema ID. A single --contentType option may be given to match a single schema id pattern.\nMultiple --contentType options may be given to match multiple schema patterns at the same time.`

Also, "Content type pattern" doesn't make sense as we can't match these on regex, only by exact match. It would just be "Content Type".

2020-10-22 11:45 UTC, rs-amp commented on src/commands/content-item/unarchive.ts
> +        'The ID of a Content type to unarchive all content items.\nA single --contentType option may be given to match a single content type pattern.\nMultiple --contentType options may be given to m
Same as above, but unarchive.

2020-10-22 11:45 UTC, rs-amp commented on src/commands/content-item/archive.ts
> +        'The ID of a Content type to archive all content items.\nA single --contentType option may be given to match a single content type pattern.\nMultiple --contentType options may be given to mat
You'll also need to change this in unarchive, and both their tests.

2020-10-22 12:08 UTC, PikinerLiliya commented on src/commands/content-item/archive.ts
> +        'The ID of a Content type to archive all content items.\nA single --contentType option may be given to match a single content type pattern.\nMultiple --contentType options may be given to mat
Thanks, done

2020-10-22 12:09 UTC, PikinerLiliya commented on src/commands/content-item/unarchive.ts
> +        'The ID of a Content type to unarchive all content items.\nA single --contentType option may be given to match a single content type pattern.\nMultiple --contentType options may be given to m
Thanks, done

2020-10-22 15:40 UTC, merged