feat(event): feature of archive and delete events along with their editions
amplience/dc-cli pull request #64
Opened 2020-12-09 16:10 UTC by PikinerLiliya

In this PR added feature of `archive`, `delete` `Events` with their `Editions`

Command has required arguments, event `id` or `name` , name could be a RegEx same as in other commands.

There could be different cases depending on editions statuses in an Event:

- all editions have status `Draft` - they will be deleted with their event
- some editions are `Scheduled`, but not `Published` - editions will be unscheduled and then deleted with their event
- some editions are `Scheduled` and already `Published` - editions will be archived, `Draft` editions will be deleted and the event will be archived too.

CLI will log all the required actions and ask a confirmation.

`Note: Archive events is not a revertable action`, so be careful using it.

2020-12-10 09:22 UTC, easen-amp requested changes

2020-12-10 09:22 UTC, easen-amp commented on src/commands/event/archive.ts
> +export const processItems = async ({
Need a return type, looks like void or empty array

2020-12-10 09:22 UTC, easen-amp commented on src/commands/event/archive.ts
> +    return [];
I think this should be `return;`

2020-12-10 09:22 UTC, easen-amp commented on package.json
> +    "dc-management-sdk-js": "git://github.com/PikinerLiliya/dc-management-sdk-js.git#feature/archiveEvents",
Can you push your branch to the main `dc-management-sdk-js` please.

2020-12-10 12:49 UTC, PikinerLiliya commented on package.json
> +    "dc-management-sdk-js": "git://github.com/PikinerLiliya/dc-management-sdk-js.git#feature/archiveEvents",
Yes, will do

2020-12-10 12:54 UTC, PikinerLiliya commented on src/commands/event/archive.ts
> +export const processItems = async ({
Done

2020-12-10 12:54 UTC, PikinerLiliya commented on src/commands/event/archive.ts
> +    return [];
Done

2020-12-11 18:11 UTC, rs-amp commented on src/commands/event/archive.ts
> +export const processItems = async ({
The return value is never used for this function, so it would make more sense for the return type to be `Promise<void>`, and for the `return [];` to be changed to `return;`.

2020-12-17 11:42 UTC, PikinerLiliya commented on src/commands/event/archive.ts
> +export const processItems = async ({
Done

2020-12-17 11:42 UTC, PikinerLiliya commented on package.json
> +    "dc-management-sdk-js": "git://github.com/PikinerLiliya/dc-management-sdk-js.git#feature/archiveEvents",
Pointed to new version

2020-12-17 12:13 UTC, PikinerLiliya commented on src/commands/event/archive.ts
> +  for (let i = 0; i < 200; i++) {
Put max to 30 now. As for publishing.

2020-12-17 12:13 UTC, PikinerLiliya commented on src/commands/event/archive.spec.ts
> +import { builder, command, handler, LOG_FILENAME, processItems, getEvents } from './archive';
Done

2020-12-17 12:14 UTC, PikinerLiliya commented on src/commands/content-item/import.ts
> +      content.id = mapping.getContentItem(content.id as string) || '';
Yes, because content.id is a string, response from mapping.getContentItem could be undefined.

2020-12-17 14:35 UTC, easen-amp approved these changes

2020-12-17 14:39 UTC, simonmudd approved these changes

2020-12-17 14:41 UTC, merged