Fix content type schemas and content types
amplience/dc-cli pull request #69
Opened 2021-01-12 14:25 UTC by PikinerLiliya

This PR contains:

- fix of export content type schemas in case when schema urls contain special characters as **:**, **!**, **?** etc. 
Special characters (especially **:** ) caused an issue on creating files on export schemas command on windows. 

- added list or repositories to a content type export command to use this list on import command to assign content types to repositories

2021-01-12 15:42 UTC, rs-amp reviewed
Looks good, just a few minor observations.

2021-01-12 15:42 UTC, rs-amp commented on src/commands/content-type/export.ts
> +  repositories.map((repo: ContentRepository) => {
This is a little weird. You can do a `.filter(...).map(...)` and get an array directly, rather than a map with no return type, that pushes elements to an array.

If you want to do it this way, you should use `forEach` instead of `map`.

2021-01-12 15:42 UTC, rs-amp commented on src/commands/content-type/export.ts
> +    exportRecord.contentType.repositories = getReposNamesForContentType(repositories, contentType);
It seems weird that this is outside of `getExportRecordForContentType`. It means that now, that method is not returning a complete content type, and must be called with this afterwards.

2021-01-12 15:42 UTC, rs-amp commented on src/commands/content-type/import.spec.ts
> +        describe: 'Skip assignment content types to the repositories',
`Skip assigning content types to repositories.` might be better. also, add a full stop.

(should also do this to the command itself)

2021-01-12 15:42 UTC, rs-amp commented on src/commands/content-type/import.ts
> +    describe: 'Skip assignment content types to the repositories',
`Skip assigning content types to repositories.` might be better. also, add a full stop.

(should also do this to the test for this command)

2021-01-12 15:42 UTC, rs-amp commented on src/commands/content-type/import.ts
> +    process.stdout.write('\nFollowing Repositories were not found in destination Hub:\n');
"The following"

2021-01-12 15:42 UTC, rs-amp commented on src/commands/content-type/import.ts
> +    uniq(notFoundRepositories).map(name => process.stdout.write(name + '\n'));
Might be nice to prepend these with 2 spaces, as a small indentation. The content item import command does this when listing problematic type schemas.

2021-01-12 21:11 UTC, PikinerLiliya commented
Thanks for review @rs-amp. All updates are done.

2021-01-28 16:22 UTC, rs-amp approved these changes

2021-04-13 09:27 UTC, simonmudd submitted a review, later dismissed

2021-04-16 12:56 UTC, easen-amp requested changes

2021-04-16 12:56 UTC, easen-amp commented on src/commands/content-type/export.ts
> +interface ContentTypeExtended extends ContentType {
I agree, `Extended` is too generic, the name of the type should reflect what it's used for it

2021-04-26 15:25 UTC, rs-amp commented on src/services/export.service.ts
> +      uniqueFilename = dir + path.sep + encodeURIComponent(file) + '.' + extension;
I've replaced this with using the package `sanitize-filename`, which will replace all the invalid characters in the filename with '_'. The filename has no function effect on import, and we enforce uniqueness with the call below anyways, so this works fine.

2021-04-26 15:25 UTC, rs-amp commented on src/commands/content-type/export.ts
> +interface ContentTypeExtended extends ContentType {
Done.

2021-04-26 15:36 UTC, rs-amp commented
Addressed comments, and added an additional conversion to posix-style paths for the content type schema descriptor files. This should make them more portable when sharing between unix and windows users.

2021-05-28 07:42 UTC, easen-amp approved these changes

2021-06-17 11:40 UTC, Benj0s approved these changes

2021-06-17 13:32 UTC, merged