Strip locale before importing, then set it afterwards.
amplience/dc-cli pull request #70
Opened 2021-02-01 11:38 UTC by rs-amp

When importing a content item with the locale field populated, we get back the error`LOCALE_IMMUTABLE` when the content is being created... Which is weird, because we're not _changing_ the locale, just setting it in the first place.

This seems to have started happening recently, and breaks all content imports with the locale field populated.

2021-02-02 08:39 UTC, PikinerLiliya requested changes

2021-02-02 08:39 UTC, PikinerLiliya commented on src/commands/content-item/import.ts
> +  item.locale = locale;
Might be reasonable to set locale here to actual locale from `await result.newItem.related.setLocale(locale);` response? Just in case

2021-03-22 12:37 UTC, AlexW-Valtech commented
Have started using this tool and quickly ran into this, is this PR expected to be merged soon?

2021-03-23 09:49 UTC, rs-amp commented on src/commands/content-item/import.ts
> +  item.locale = locale;
Pushed a change to do this.

2021-03-23 17:04 UTC, rs-amp commented
Hopefully it should be in the next minor version, along with the other fix. Just need to figure out if the media rewriting can make it.

2021-03-24 09:48 UTC, PikinerLiliya approved these changes

2021-03-26 15:20 UTC, easen-amp reviewed
Do we need to update the dc-management-sdk-s to make locale option on a Content Item?

2021-03-26 15:20 UTC, easen-amp commented on src/commands/content-item/import.ts
> +  (item as any).locale = undefined;
Typing to `any` is dangerous and should be avoided.

In dc-management-sdk-js [locale is required field](https://github.com/amplience/dc-management-sdk-js/blob/7cc7987/src/lib/model/ContentItem.ts#L47), should we also be updating the dc-management-sdk-js?

2021-03-26 15:26 UTC, easen-amp commented on src/commands/content-item/import.ts
>      result = { newItem: await oldItem.related.update(item), oldVersion };
Looking at the error code `LOCALE_IMMUTABLE`, immutable locale check validation only applies to updates not creating content items.

2021-04-13 08:48 UTC, rs-amp commented on src/commands/content-item/import.ts
>      result = { newItem: await oldItem.related.update(item), oldVersion };
It's happening on creation. I do not know why, I have checked myself. The error stops the item from being created at all.

2021-04-13 08:50 UTC, rs-amp commented on src/commands/content-item/import.ts
> +  (item as any).locale = undefined;
This field is not required at all, I don't know why it is right now. If this cast to any is to be avoided, then it should be updated.

2021-04-13 09:32 UTC, rs-amp commented on src/commands/content-item/import.ts
> +  (item as any).locale = undefined;
I've made a PR for this change:

https://github.com/amplience/dc-management-sdk-js/pull/80

2021-05-06 10:25 UTC, easen-amp commented on src/commands/content-item/import.ts
> +  (item as any).locale = undefined;
amplience/dc-management-sdk-js#80 has been merged down

2021-05-06 10:27 UTC, easen-amp commented on src/commands/content-item/import.ts
>      result = { newItem: await oldItem.related.update(item), oldVersion };
I can't see how it can be triggered on a content-item create, I have checked the validation code in DC itself.

2021-05-06 10:28 UTC, easen-amp approved these changes

2021-05-12 09:52 UTC, Benj0s approved these changes

2021-05-12 10:00 UTC, easen-amp commented
@rs-amp https://github.com/amplience/dc-management-sdk-js/releases/tag/v1.11.0 has been released, is it worth bumping the dc-management-sdk-js version?

2021-05-12 11:27 UTC, rs-amp commented
I will update dc-management-sdk-js and remove the any cast, just gimme a sec.

2021-05-12 13:34 UTC, rs-amp commented on src/commands/content-item/import.ts
>      result = { newItem: await oldItem.related.update(item), oldVersion };
I can create a concentrated, small test program using the dc-management-sdk-js if that helps.

2021-05-12 16:18 UTC, rs-amp commented on src/commands/content-item/import.ts
>      result = { newItem: await oldItem.related.update(item), oldVersion };
https://github.com/rs-amp/locale-test

You can reproduce the issue with this program. Included is a content item with a predefined locale. Run the application with:

`node index.js <clientId> <clientSecret> <repoId> <contentJsonFilename>`

I get the following output, and the content is not created:

> Setting up client.
Fetching repo.
Reading content from content.json.
Creating content item.
(node:61897) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400: {"errors":[{"level":"ERROR","code":"LOCALE_IMMUTABLE","message":"locale cannot be modified once set","property":"locale","entity":"ContentItem","invalidValue":"en-GB"}]}

Obviously this is with a repo with `en-GB` as an allowed locale, and the specified content type registered.

2021-06-02 07:53 UTC, easen-amp commented on src/commands/content-item/import.ts
>      result = { newItem: await oldItem.related.update(item), oldVersion };
I think I've got to the bottom of this issue, because you have passed an `id` DC thinks this is an _existing_ Content Item and so then it checks to make sure the locale property hasn't been passed. Can you update your test app to remove the `id` property and try again?

2021-06-17 13:24 UTC, merged