Media Link Rewriting on Import
amplience/dc-cli pull request #71
Opened 2021-02-02 09:35 UTC by rs-amp

This PR adds the ability for the import command to detect and rewrite media links within content items. This is done by detecting media links within content items, looking up their names using a new project called the `dam-management-sdk` (which allows us to use DAM endpoints with your current api client), and rewriting the id/endpoint etc within the content items to match similar assets on the target's DAM. The target endpoint is gleamed from the DAM settings visible from the importing account (the "default endpoint").

To activate this functionality, pass the `--media` flag on import, copy or move.

Essentially, if you export a bunch of asset linked content from one account with known asset `name`s (not labels), then passing `--media` will find and attempt assets with matching names in the target account, and rewrite the links to point to them instead. You can use this to properly copy content and items, assuming a process like an FTP file upload was used to populate the asset store.

The `dam-management-sdk` project needs to be deep-reviewed and recreated on the main github/npm before merging this PR. It's similar to dc-management-sdk in structure, though all endpoints are available without using a resource, and `related` links are simply shortcuts to those endpoints. This is because DAM's API has a flat structure, rather than the resource focused HAL link approach of DC - the related links simply exist as shortcuts and to provide more familiarity to users of the DC management SDK.

Currently, the `dam-management-sdk` project can be found here:
https://github.com/rs-amp/dam-management-sdk-js

2021-02-02 11:38 UTC, rs-amp commented
## Testing Media Link Rewriting

First step is to create a content item with a standard media link. The media linked should have a known name.

```
image: {
  id: '299ba2ac-aa5b-4c18-81da-f12156ad9622',
  name: 'imageProperty',
  endpoint: 'old',
  defaultHost: 'i1.adis.ws',
  mediaType: 'image',
  _meta: {
    schema: 'http://bigcontent.io/cms/schema/v1/core#/definitions/image-link'
  }
},
```

Next, make sure you have a target api client with DC and DAM access. Ensure that an asset with a matching name exists in the target asset store (generally, an upload or FTP upload with the same filename will produce the same name).

Perform your import, move or copy of the content item with the `--media` flag. After identifying dependencies, it should state that it is rewriting media links. If it fails to get your DAM configuration it will throw an error. Otherwise, the id, endpoint and default host will be updated to match the asset found on the target DAM.

2021-02-02 11:49 UTC, easen-amp requested changes
Looks good, just a few small changes are required. I need to review the dam-mnagement-sdk-js separately, which might result in further requested changes.

2021-02-02 11:49 UTC, easen-amp commented on src/common/media/media-rewriter.ts
> +    let totalFound = 0;
is this needed?

2021-02-02 11:49 UTC, easen-amp commented on src/services/dam-client-factory.ts
> +      apiUrl: process.env.DAM_API_URL,
I think there should be a default value here if `process.env.DAM_API_URL` results in null|undefined.

2021-02-02 14:16 UTC, PikinerLiliya reviewed
@rs-amp Did you check this with asset names containing special characters (ex. `+`, `?`, `!`, white space, etc)?

2021-02-03 11:22 UTC, rs-amp commented on src/common/media/media-rewriter.ts
> +    let totalFound = 0;
Nope, it was there just in case, but I ended up returning the missing content instead of the found.

2021-02-03 11:44 UTC, rs-amp commented on src/services/dam-client-factory.ts
> +      apiUrl: process.env.DAM_API_URL,
This is the same as the `dynamicContentClientFactory`. The `dc-management-sdk-js` and `dam-management-sdk-js` both provide defaults in their handling of these parameters, if any of the URLs are undefined/null.

Should I change both?

2021-02-03 15:46 UTC, rs-amp commented
> @rs-amp Did you check this with asset names containing special characters (ex. +, ?, !, white space, etc)?

That's a good point, though spaces work, other character types do not since the search is done with a regex. I'm adding some code in `dam-management-sdk` to escape them.

2021-04-13 11:51 UTC, simonmudd requested changes, later dismissed

2021-04-13 11:51 UTC, simonmudd commented on src/common/media/media-rewriter.spec.ts
> +      expect(throws).toBeTruthy();
Are different types of error or different messages being thrown for these tests? It might be safer to assert a error message that is thrown as if the rewriter is overwrote or something then this will always throw an error. 

Error messages can be asserted by:
```typescript
await expect(rewriter.rewrite()).rejects.toThrowErrorMatchingInlineSnapshot();
```

2021-04-13 15:49 UTC, rs-amp commented on src/common/media/media-rewriter.spec.ts
> +      expect(throws).toBeTruthy();
Thanks for the suggestion, I've updated these tests.

2021-04-16 10:56 UTC, easen-amp commented on src/common/media/media-rewriter.ts
> +        const result = await this.dam.assets.list({
We should back off API requests using exponential back off -- https://www.npmjs.com/package/promise-retry

2021-04-16 11:04 UTC, easen-amp commented on src/common/media/media-rewriter.ts
> +    for (let i = 0; i < itemLinks.length; i++) {
These two could rewritten to be:-

`allNames = this.injector.all.flatMap(links => links.map(link => link.link.name))`

2021-04-16 11:05 UTC, easen-amp commented on src/common/media/media-rewriter.ts
> +      if (first) {
Could this be move above the `for()` loop?

2021-04-16 11:11 UTC, easen-amp commented
You have a number of for loops which have multiple 'paths' through the code, which means the cycloramic complexity is high. 
Having a high cycloramic complexity means the code can become brittle and difficult to debug.
Can you to refactor these loops to be minimise the number of paths.

In some places I have seen you use `for(let i =0; i< X; i++) {...}` a lot, I think you are using these because `forEach()` wont wait for promises to be resolved. You can use `for(const item of myCollection) {...}` instead, which reads better and plays nicely with await/async blocks.

2021-04-16 14:31 UTC, rs-amp commented on src/common/media/media-rewriter.ts
> +    for (let i = 0; i < itemLinks.length; i++) {
The project needs to be updated to `es2019` to do this.

2021-04-16 14:37 UTC, rs-amp commented on src/common/media/media-rewriter.ts
> +      if (first) {
This doesn't combine well with the suggested change to a `for of` loop below, but would be possible if it stayed as a normal for loop.

2021-04-19 10:11 UTC, rs-amp commented
> You have a number of for loops which have multiple 'paths' through the code, which means the cycloramic complexity is high.
> Having a high cycloramic complexity means the code can become brittle and difficult to debug.
> Can you to refactor these loops to be minimise the number of paths.
> 
> In some places I have seen you use `for(let i =0; i< X; i++) {...}` a lot, I think you are using these because `forEach()` wont wait for promises to be resolved. You can use `for(const item of myCollection) {...}` instead, which reads better and plays nicely with await/async blocks.

Noted. I've resolved cases of this in this PR where it makes sense to, though it does mean i still need the `first` variable for the request builder loop.

- Now uses `promise-retry` to retry requests. The tests have been updated to mock this to remove the delay between requests.
- The project now targets es2019, and `getLinkNames` has been simplified.
- The request builder now uses a `for of` loop.

2021-04-19 10:11 UTC, rs-amp commented
Just noticed in the tests, node 10.x does not have flatMap available. It should probably be reverted.

2021-04-19 11:14 UTC, rs-amp commented
Updated.

2021-04-20 08:30 UTC, PikinerLiliya approved these changes

2021-05-28 07:49 UTC, easen-amp commented on src/common/media/media-rewriter.ts
> +    for (let i = 0; i < itemLinks.length; i++) {
Feel free to upgrade it.

2021-05-28 07:55 UTC, easen-amp commented
> Just noticed in the tests, node 10.x does not have flatMap available. It should probably be reverted.

Can you revert your change and target es2019 please, the current LTS version of NodeJS is 14.x.

2021-05-28 07:57 UTC, easen-amp requested changes
Revert the removal of es2019 (Node 14.x is now LTS)
In the meantime I will raise a PR to target to NodeJS 14.x

Update the PR title to be a `feat:...`

2021-06-16 11:49 UTC, rs-amp commented
> Revert the removal of es2019 (Node 14.x is now LTS)
> In the meantime I will raise a PR to target to NodeJS 14.x
> 
> Update the PR title to be a `feat:...`

Now waiting on this (10.x build failing)

2021-06-16 15:26 UTC, easen-amp approved these changes

2021-06-16 15:53 UTC, merged