feat(log): log errors in a more consistent fashion
amplience/dc-cli pull request #72
Opened 2021-03-10 09:27 UTC by rs-amp

This PR changes the reporting of errors and warnings into the log to be more consistent, and machine readable.

When an error occurs, there is now an `ERROR` or `WARNING` action inserted into the logs.

When any error or warning occurs, the overall error level of the log is increased to match the error. This is printed at the end of the file as `SUCCESS` if there are no warnings or errors, `FAILURE` if there are errors, or the highest error level otherwise.

The errors logs themselves have been made more consistent - logs with `Error` instances will now print them on the next line all of the time, rather than inconsistently as part of the string template.

This shouldn't be a breaking change. The final return code is on the last line of the log, which was previously empty. (the log ended with a new line). If the `ArchiveLog` attempts to parse a log without an exit code, it should default to `SUCCESS`.

2021-03-10 15:01 UTC, rs-amp commented
Note: The archive/unarchive commands only begin logging after they have found the content to archive, so any errors during that time will cause the command to exit without producing a log. Errors for these commands will only be logged when the error happens during the archive/unarchive process, otherwise no log file will be created.

This PR doesn't change this behaviour, but it might be changed in future.

2021-03-12 12:30 UTC, easen-amp commented
Having `log.addError(LogErrorLevel.WARNING, ...)` and `log.addError(LogErrorLevel.ERROR,...)` doesn't look right to me, normally a logger would have a series of methods for each level that it supports (`log.debug()`, `log.info()`, `log.warn()`, `log.error()`) and the 1st argument passed into it would be a `string` and the next/remaining arguments would be contextual data (additional data that needs to be logged), e.g. 
```typescript
try {
  myMethod();
} catch (err) {
  log.error('Failed to do X', {error: err});
} ```

See https://www.npmjs.com/package/js-logger for a more concrete example.

Can this be updated to follow this pattern?

2021-03-12 12:32 UTC, easen-amp requested changes
Having `log.addError(LogErrorLevel.WARNING, ...)` and `log.addError(LogErrorLevel.ERROR,...)` doesn't look right to me, normally a logger would have a series of methods for each level that it supports (`log.debug()`, `log.info()`, `log.warn()`, `log.error()`) and the 1st argument passed into it would be a `string` and the next/remaining arguments would be contextual data (additional data that needs to be logged), e.g. 
```typescript
try {
  myMethod();
} catch (err) {
  log.error('Failed to do X', {error: err});
} 
```

See https://www.npmjs.com/package/js-logger for a more concrete example.

Can this be updated to follow this pattern?

2021-03-12 14:21 UTC, rs-amp commented
I've updated the warn and error logs to use special methods, and the `addError` function has been privated as a result. The enum is still used for severity and parsing. Is this alright?

2021-03-12 14:29 UTC, PikinerLiliya approved these changes
Good job

2021-03-12 14:30 UTC, easen-amp requested changes
Looks better, just some checkstyle warnings from the not used `LogErrorLevel` imports

2021-03-12 14:30 UTC, easen-amp commented on src/commands/content-item/archive.ts
> +import { LogErrorLevel, ArchiveLog } from '../../common/archive/archive-log';
checkstyle warning

2021-03-12 14:30 UTC, easen-amp commented on src/commands/content-item/archive.ts
> +        log.warn(`Failed to archive ${contentItems[i].label} (${contentItems[i].id}), continuing.`, e);
much better 👍

2021-03-12 14:30 UTC, easen-amp commented on src/commands/content-item/import.ts
> +import { LogErrorLevel } from '../../common/archive/archive-log';
check style warnings

2021-03-12 14:43 UTC, rs-amp commented on src/commands/content-item/import.ts
> +import { LogErrorLevel } from '../../common/archive/archive-log';
Oops, of course I forgot to remove these 🥴

2021-03-12 15:49 UTC, easen-amp approved these changes

2021-03-16 09:47 UTC, merged