feat(hub): clone hub command
amplience/dc-cli pull request #76
Opened 2021-03-17 10:23 UTC by rs-amp

_This PR also contains changes from #71._

This PR adds a clone hub command. This command essentially runs the functionality from all the other import and export commands in order to provide a singe revertible command that clones an entire hub.

The majority of the arguments to this command match the content item export/import arguments, as that has the most options. Some things are assumed, such as that you'd want to sync certain schemas or `--force` certain things.

The command essentially runs revertible "steps" in order, passing through your arguments from the clone command to each of the steps. The four steps are:

- Clone Settings
- Clone Content Type Schemas
- Clone Content Types
- Clone Content Items

The first three steps essentially string together import and export commands, working in a subdirectory of the provided folder. The results of the export remain in the output folder, so that they can be inspected and verified. The settings and types commands also export from the _destination_ repo, so that those original files can be used to revert those steps.

The revert command runs these commands in the same order, as each of these them depends on the state of the last to properly validate. For example, if we're reverting content items, they might only validate against an older version of that content type schema, so they must be imported first.

- The import and export commands for content types and content type schemas have been updated to use the FileLog.
- The FileLog now supports categories. Along with sharing a mapping file, this allows all the actions of clone to share logs and a mapping file, making them easier to revert.

2021-05-13 14:45 UTC, easen-amp requested changes

2021-05-13 14:45 UTC, easen-amp commented on src/commands/hub/steps/schema-clone-step.ts
> +    for (let i = 0; i < toArchive.length; i++) {
Can be replaced with a for (... of ..) loop

2021-05-13 14:45 UTC, easen-amp commented on src/commands/hub/steps/schema-clone-step.ts
> +    for (let i = 0; i < toUpdate.length; i++) {
Can be replaced with a for (... of ..) loop

2021-05-13 14:45 UTC, easen-amp commented on src/commands/hub/clone.ts
> +    .option('dstHubId', {
I am not a fan of abbreviated cli flags, plus it's inconsistent with the rest of the options. 

Can dst be expaned to destination, so `dstHubId` becomes `destinationHubId`, or if thats too long use `target...`

2021-05-13 14:45 UTC, easen-amp commented on src/commands/hub/clone.ts
> +    .option('step', {
Can step be a enum string instead, just incase we introduce another step.

2021-05-13 14:45 UTC, easen-amp commented on src/commands/hub/clone.ts
> +const steps = [new SettingsCloneStep(), new SchemaCloneStep(), new TypeCloneStep(), new ContentCloneStep()];
This could be updated to an a object where each property is a enum value and the value to be the step.

The ordering of the steps can then be defined as an array...
```
enum STEP {
  HUBS = 'hubs',
  ...
}
const ordering = [STEP.HUBS, ...];
const steps = {
  'hub' : new SettingsCloneStep(), 
  ...
}
```

The loop logic can be updated to be:
```
for (const currentStep of ordering.slice(ordering.indexOf(argv.step) + 1)) {
  const step = steps[currentStep];
  ...
}
```

2021-05-13 14:45 UTC, easen-amp commented on src/common/dc-management-sdk-js/resource-status.ts
> +export enum Status {
dc-managment-sdk-js needs to be updated so it exports these.

2021-05-13 14:45 UTC, easen-amp commented on src/common/log-helpers.ts
> +function asyncQuestionInternal(rl: ReadLine, question: string): Promise<string> {
Just being picky here, but these function aren't really related to logs, can these be moved into another file called question-helpers.ts

2021-05-13 14:45 UTC, easen-amp commented on src/interfaces/clone-hub-builder-options.ts
> +  dstHubId?: string;
See my comment around the naming of these in the clone command file

2021-05-13 14:45 UTC, easen-amp commented on src/interfaces/copy-item-builder-options.interface.ts
> +  revertLog?: string | FileLog;
I mentioned it on other PR's, I'm not a fan of this, we should'nt have types that can be a string or a object.

2021-05-14 14:35 UTC, rs-amp commented on src/commands/content-type/import.ts
> +import { ResourceStatus, Status } from '../../common/dc-management-sdk-js/resource-status';
I commented on the reason for this in the other PR. You haven't responded yet.

2021-05-14 14:37 UTC, rs-amp commented on src/commands/hub/clone.ts
> +    .option('dstHubId', {
This argument name is consistent with the copy and move content items command, and the copy config file (which is due to be replaced in another PR anyways). I think it's out of scope to be renaming those parameters here.

2021-05-14 14:39 UTC, rs-amp commented on src/commands/content-type/import.ts
> +import { ResourceStatus, Status } from '../../common/dc-management-sdk-js/resource-status';
oops, wrong comment response

2021-05-14 14:39 UTC, rs-amp commented on src/commands/content-item/import-revert.ts
> +  if (typeof argv.revertLog === 'string') {
I commented on the reason for this in the other PR. You haven't responded yet.

2021-05-14 15:19 UTC, rs-amp commented on src/commands/content-type/import.ts
> +import { ResourceStatus, Status } from '../../common/dc-management-sdk-js/resource-status';
This was done in the interest of time. I've created a PR for this change in the management sdk:
https://github.com/amplience/dc-management-sdk-js/pull/90

2021-05-14 15:19 UTC, rs-amp commented on src/commands/content-type/import.ts
> +  if ((retrievedContentType as ResourceStatus).status === Status.ARCHIVED) {
https://github.com/amplience/dc-management-sdk-js/pull/90

2021-05-14 15:43 UTC, rs-amp commented on src/commands/event/archive.ts
> +    id: id as string,
`ArchiveOptions.id` can now be a `string[]` as it is used for the other options. Events are not currently supported by clone, so they can only get their ids from the yargs positional attribute, which is `string` only. (yargs optional can be `string[]`).

So, currently the callers of this function only pass `string`. I can change this to also handle the case of passing multiple ids, as it will be used in the future.

2021-05-24 06:49 UTC, PikinerLiliya approved these changes

2021-05-25 08:25 UTC, rs-amp commented
I've updated this with the change to make the FileLog get its data from coerce, and pass around `FileLog` rather than `FileLog | string | undefined`, same as clean hub. Let me know what you think @easen-amp .

The target branch now includes #71 AND #77, so those two must be merged before this PR. It's worth noting that those two PRs are still separate - the target branch isn't part of one of them.

2021-06-02 08:05 UTC, easen-amp commented on package.json
> +    "dc-management-sdk-js": "github:rs-amp/dc-management-sdk-js#feature/status",
Just a note to merge down https://github.com/amplience/dc-management-sdk-js/pull/90

2021-06-02 08:05 UTC, easen-amp commented on src/commands/event/archive.ts
> +    id: id as string,
Do you check within the` getEvents()` to make sure it's an `string`?

2021-06-02 09:43 UTC, rs-amp commented
`revertLog` has been changed to pass around a `Promise<FileLog | undefined>` instead of a string | FileLog, which attempts to open the revert log on await. If it can't be opened, the error state is set to `INVALID`, and the commands properly handle it.

2021-06-14 14:51 UTC, easen-amp commented on src/commands/hub/clone.ts
> +    .option('dstHubId', {
I'm not a fan of mixing shorthand and longhand cli flags. 
Thats a shame the copy and move use this shorthand for destination, Yarg does have an `alias` features so we can support both.

2021-06-16 15:42 UTC, easen-amp commented on src/interfaces/clone-hub-builder-options.ts
> +  dstHubId?: string;
I've change my mind, I think using 'src' instead of 'source' is acceptable, so therefore 'dst' instead of 'destination' should be acceptable.

2021-06-16 15:43 UTC, easen-amp commented on src/commands/hub/clone.ts
> +const steps = [new SettingsCloneStep(), new SchemaCloneStep(), new TypeCloneStep(), new ContentCloneStep()];
I guess my gripe here is using numbers as command line arguments, numbers that could change when additional steps are added in the future.

2021-06-17 11:05 UTC, easen-amp approved these changes

2021-06-17 11:06 UTC, merged