feat(hub): clean hub command
amplience/dc-cli pull request #77
Opened 2021-03-19 09:45 UTC by rs-amp

This PR adds a command for cleaning a whole hub. This runs all of the content/type/schema archive commands at once, which can be rather useful for automation. All of the commands are combined into a single log file, and could potentially be reverted from this single log file with a future change to the command.

Additional Changes:
- Content Item Archive now attempts to remove delivery keys before archiving. The removed delivery key will be stored with the ARCHIVE action, and can be restored when running UNARCHIVE with the revert log. The tests have been cleaned up and updated to support this new situation.
- The archive commands can now take a FileLog directly from their argv, which allows us to pass a FileLog in from the clean hub command.
- Fixed a bug with the content dependency tree where a null object would cause the traversal to fail.

NOTE: This PR contains the same log group changes as clone hub, as the groups can be used to revert at some point in the future.

2021-03-31 09:49 UTC, PikinerLiliya reviewed
Good clean up on archive/unarchive tests.

2021-03-31 09:49 UTC, PikinerLiliya commented on src/commands/content-item/unarchive.ts
> +            contentItems.push(...items.filter(item => item.status !== 'ACTIVE'));
Is double check of status necessary here? Requested items should already have status 'ARCHIVED'.

2021-04-14 10:20 UTC, simonmudd submitted a review, later dismissed

2021-04-14 10:20 UTC, simonmudd commented on src/commands/content-item/archive.ts
> +  const log = typeof logFile === 'object' ? logFile : new ArchiveLog(`Content Items Archive Log - ${timestamp}\n`);
It might be better to check the instance of the `logFile` instead of just checking that this is an object, mainly because an Array or Null are classed as objects too. Typescript should guard against these assignments but it is easy enough to circumvent with type casting.

We could always make a typeguard to query the `logFile` type and therefore it would be re-usable in other areas.

2021-04-14 10:20 UTC, simonmudd commented on src/commands/content-type-schema/archive.ts
> +    typeof logFile === 'object' ? logFile : new ArchiveLog(`Content Type Schema Archive Log - ${timestamp}\n`);
Would benefit from a type guard.

2021-04-14 10:20 UTC, simonmudd commented on src/commands/content-type/archive.ts
> +  const log = typeof logFile === 'object' ? logFile : new ArchiveLog(`Content Type Archive Log - ${timestamp}\n`);
Would benefit from a type guard.

2021-04-14 10:20 UTC, simonmudd commented on src/commands/event/archive.ts
> +    const log = typeof logFile === 'object' ? logFile : new ArchiveLog(`Events Archive Log - ${timestamp}\n`);
Would benefit from a type guard.

2021-04-14 10:32 UTC, rs-amp commented on src/commands/content-item/unarchive.ts
> +      const deliveryKey = contentItems[i].body._meta.deliveryKey;
`_meta` will always be defined, so the result here is undefined or a string. The check below only updates the delivery key field in the content item if it is changed from the version we got back from DC. This will:

- Add the delivery key if it is desired.
- Update it if it is different.
- Do nothing if it is the same. (this includes both original and desired being undefined)
- Remove it if it is now undefined, and the original was defined.

The situations past the first are unlikely, as the delivery key update's only cause is due to an archive revert, which assumes the user has not done anything else to the content item since the archive.

2021-04-14 10:33 UTC, rs-amp commented on src/commands/content-type-schema/archive.ts
> +    typeof logFile === 'object' ? logFile : new ArchiveLog(`Content Type Schema Archive Log - ${timestamp}\n`);
I can update these to be more specific. This type check was just exclusive enough to narrow down the type to FileLog, but I understand that it's not exactly clear.

2021-04-14 10:34 UTC, rs-amp commented on src/commands/content-item/unarchive.ts
> +            contentItems.push(...items.filter(item => item.status !== 'ACTIVE'));
This is kind of a leftover from before I selected the archived status using the list endpoint. I can fix it.

2021-04-14 13:10 UTC, rs-amp commented
Addressed feedback.

2021-04-16 12:53 UTC, easen-amp approved these changes

2021-05-12 10:50 UTC, Benj0s approved these changes

2021-05-12 10:52 UTC, easen-amp requested changes
I think the way you are passing around the logFile can be refined, see my comments.

2021-05-12 10:52 UTC, easen-amp commented on src/common/content-item/content-dependancy-tree.ts
> +    } else if (body != null) {
I suspect this was changed due to a bug, but I can't see a unit test for this change.

2021-05-12 10:52 UTC, easen-amp commented on src/common/archive/archive-options.ts
> +  logFile?: string | FileLog;
I'm not a fan of this, I think it should be a single type. If you need to support both, then create a wrapper class that accepts either a string or a FileLog instance. See [Adaptor pattern](https://en.wikipedia.org/wiki/Adapter_pattern) or [Facade pattern](https://en.wikipedia.org/wiki/Facade_pattern).

2021-05-12 10:52 UTC, easen-amp commented on src/commands/hub/clean.ts
> +  const log = logFile instanceof FileLog ? logFile : new FileLog(logFile);
See my comment regarding Adapter or Facet pattern.

I also cannot see any tests where logFile is an FileLog instamce

2021-05-12 10:52 UTC, easen-amp commented on src/commands/content-item/archive.ts
> +  const log = logFile instanceof FileLog ? logFile : new ArchiveLog(`Content Items Archive Log - ${timestamp}\n`);
Again see my comment regarding using the Adapter or Facet pattern

2021-05-12 10:52 UTC, easen-amp commented on src/commands/content-type-schema/archive.ts
> +  const log = logFile instanceof FileLog ? logFile : new ArchiveLog(`Content Type Schema Archive Log - ${timestamp}\n`);
See my other comment regarding using Adapter or Facet pattern

2021-05-12 10:52 UTC, easen-amp commented on src/commands/event/archive.ts
> +    const log = logFile instanceof FileLog ? logFile : new ArchiveLog(`Events Archive Log - ${timestamp}\n`);
See my other comment regarding using Adapter or Facet pattern

2021-05-12 11:01 UTC, rs-amp commented on src/common/archive/archive-options.ts
> +  logFile?: string | FileLog;
This is on a configuration interface where this value is usually an input from yargs, which _must_ be either type string or string[]. There's not really any room to make a wrapper class over it.

I don't know what the alternative here would be, apart from having an additional property that contains the `FileLog` object when it is needed (like from handler calls from a non-yargs source), but they are _mutually exclusive_ so the type | is still better in that regard.

2021-05-12 11:02 UTC, rs-amp commented on src/common/content-item/content-dependancy-tree.ts
> +    } else if (body != null) {
The change is for traversing objects with null property or array values. I can add a test for this one.

2021-05-12 11:24 UTC, rs-amp commented on src/common/content-item/content-dependancy-tree.ts
> +    } else if (body != null) {
Done. Have also verified that the test fails without this change.

2021-05-17 07:48 UTC, easen-amp commented on src/common/archive/archive-options.ts
> +  logFile?: string | FileLog;
I think I got the wrong of the stick here, I completely forgot about the non-yarg calls to the various handler() methods, I do apologise.

However, having a type that can be a string or a class is messy, but I think we can avoid it by getting yargs to convert the option from a `string` to a `FileLog` 

https://yargs.js.org/docs/#api-reference-coercekey-fn 

How I think it would work...
```
    .option('logFile', {
      type: 'string',
      default: LOG_FILENAME,
      describe: 'Path to a log file to write to.',
      coerce: (input: string) => new FileLog(input)
    })
```

2021-05-17 08:21 UTC, rs-amp commented on src/common/archive/archive-options.ts
> +  logFile?: string | FileLog;
That is a good idea, I'll see if I can make that work.

2021-05-20 08:38 UTC, rs-amp commented
I've updated the FileLog uses with the new approach, which has yargs create the FileLog instance, and the handlers _only_ take them. For nested commands, a ref counting system is used where the child command takes a reference, and removes it when the command ends. If there are no references left, the log is saved.

This is going through QA at the moment, though it would be good to review as the approach is being brought over to the clone command as well.

2021-05-21 10:04 UTC, easen-amp requested changes

2021-05-21 10:04 UTC, easen-amp commented on src/common/log-helpers.ts
> +export function createLog(logFile: string, title?: string): FileLog {
Much better. Can you add a unit test for this helper?

2021-05-21 10:31 UTC, rs-amp commented on src/common/log-helpers.ts
> +export function createLog(logFile: string, title?: string): FileLog {
Sure.

2021-05-24 06:45 UTC, PikinerLiliya approved these changes

2021-05-24 09:08 UTC, rs-amp commented
Addressed.

2021-06-02 07:56 UTC, easen-amp approved these changes

2021-06-17 10:36 UTC, easen-amp approved these changes

2021-06-17 10:42 UTC, merged