feat(config): allow using configure command with a custom file
amplience/dc-cli pull request #80
Opened 2021-04-12 09:16 UTC by rs-amp

Adds the ability for the `--config` argument to be used with `dc-cli configure` to read/write a config file at any location, rather than just the one in the `.amplience` folder. Using `--help` implied you could do this anyways, so this PR just solidifies it.

A test has been added to verify this behaviour.

2021-04-16 11:17 UTC, easen-amp requested changes

2021-04-16 11:17 UTC, easen-amp commented on src/commands/configure.ts
> +type ConfigArgument = {
Why is this separate? Could it be in the `ConfigurationParameters`?

2021-04-16 11:17 UTC, easen-amp commented on src/commands/configure.ts
> +type ConfigArgument = {
What happens if config is not supplied? Shouldn't it fall back to `CONFIG_FILENAME()`

2021-06-17 13:45 UTC, easen-amp commented on src/commands/configure.ts
> +type ConfigArgument = {
yargs defaults to `CONFIG_FILENAME()` on line 28

2021-06-17 13:46 UTC, easen-amp approved these changes

2021-06-30 08:00 UTC, PikinerLiliya approved these changes

2021-08-18 09:52 UTC, merged